package targets_svc

type (
	IncomingMsg struct {
		IDx     uint64   `json:"idx"`
		Status  string   `json:"status"`
		Filters []Filter `json:"filters"`
	}

	Filter struct {
		Type   string   `json:"filter_type"`
		Target string   `json:"filter_target"`
		Values []string `json:"filter_values"`
	}
)

var CountryCodes = []string{
	"AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM", "AW", "AU", "AT", "AZ",
	"BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT", "BO", "BA", "BW", "BV", "BR", "IO",
	"BN", "BG", "BF", "BI", "KH", "CM", "CA", "CV", "KY", "CF", "TD", "CL", "CN", "CX", "CC", "CO",
	"KM", "CG", "CD", "CK", "CR", "CI", "HR", "CU", "CY", "CZ", "DK", "DJ", "DM", "DO", "EC", "EG",
	"SV", "GQ", "ER", "EE", "ET", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF", "GA", "GM", "GE",
	"DE", "GH", "GI", "GR", "GL", "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY", "HT", "HM", "VA",
	"HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM", "JP", "JE", "JO",
	"KZ", "KE", "KI", "KP", "KR", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY", "LI", "LT", "LU",
	"MO", "MK", "MG", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU", "YT", "MX", "FM", "MD",
	"MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "AN", "NC", "NZ", "NI", "NE",
	"NG", "NU", "NF", "MP", "NO", "OM", "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH", "PN", "PL",
	"PT", "PR", "QA", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC", "WS", "SM",
	"ST", "SA", "SN", "RS", "SC", "SL", "SG", "SK", "SI", "SB", "SO", "ZA", "GS", "ES", "LK", "SD",
	"SR", "SJ", "SZ", "SE", "CH", "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK", "TO", "TT", "TN",
	"TR", "TM", "TC", "TV", "UG", "UA", "AE", "GB", "US", "UM", "UY", "UZ", "VU", "VE", "VN", "VG",
	"VI", "WF", "EH", "YE", "ZM", "ZW",
}

var Browsers = []string{
	"aol_app",
	"aol_desktop",
	"alcatel",
	"aliapp",
	"alltop_app",
	"android",
	"android_webview",
	"apple_appstore_app",
	"apple_mail",
	"apple_news",
	"asus",
	"baidu_box_app",
	"baidu_browser",
	"baidu_browser_hd",
	"baidu_browser_mini",
	"benq",
	"beonex_communicator",
	"beyondpod",
	"binance_app",
	"bing",
	"bing_search_app",
	"bing_ipad",
	"bittorrent",
	"bittorrentmac",
	"blackberry",
	"booking.com_app",
	"chrome",
	"chromeplus",
	"chromium",
	"citrix_chrome_app",
	"coc_coc_browser",
	"coursera_mobile_app",
	"crosswalk_app",
	"crowsnest_mobile_app",
	"darwin_browser",
	"duckduck_app",
	"duckduckgo_browser",
	"easyrider",
	"edge",
	"edge_mobile",
	"electron",
	"espial_tv_browser",
	"evernote_app",
	"evolution",
	"facebook_groups",
	"facebook_messenger",
	"firebird",
	"firefox",
	"firefox_focus",
	"firefox_for_ios",
	"flamesky",
	"flipboard_app",
	"flixster_app",
	"fluid",
	"fluid_app",
	"google_app",
	"google_desktop",
	"google_mail",
	"google+_app",
	"hp_secure_web_browser",
	"haier",
	"huawei",
	"huaweibrowser",
	"hyundai",
	"ie",
	"ie_offline_browser",
	"iemobile",
	"instagram_app",
	"kindle",
	"kindle_fire",
	"kodi_media_center",
	"konqueror",
	"kurio_app",
	"lg",
	"lg_browser",
	"lenovo",
	"linkedinapp",
	"maxthon",
	"maxthon_nitro",
	"meizu_browser",
	"mint_browser",
	"mitsu_browser",
	"miui_browser",
	"motorola_internet_browser",
	"mozilla",
	"netscape",
	"nintendo_browser",
	"nokia_browser",
	"oculus_browser",
	"odyssey_web_browser",
	"okta_mobile_app",
	"oneplus_browser",
	"opera",
	"opera_gx",
	"opera_mini",
	"opera_mobile",
	"opera_neon",
	"opera_touch",
	"oppo_browser",
	"panasonic",
	"panasonic_tv_browser",
	"pinterest_app",
	"playstation",
	"playstation_browser",
	"powertv",
	"prismatic_app",
	"qq-app",
	"qqbrowser",
	"qqbrowser_mini",
	"qiyu_browser",
	"qtweb_browser",
	"reddit",
	"reddit_app",
	"safari",
	"sagem",
	"sagoo",
	"sailfish_browser",
	"salesforce_app",
	"samsung",
	"samsung_browser",
	"samsung_mobile_browser",
	"samsung_tv",
	"samsung_webview",
	"sandvox",
	"smarttv_webbrowser",
	"sogou_explorer",
	"sogou_mobile",
	"sony",
	"sony_ps2",
	"sony_psp",
	"sonycebrowser",
	"spotify",
	"sputnik_browser",
	"steam",
	"steam_overlay",
	"tesla_car_browser",
	"teslabrowser",
	"thunderbird",
	"twitter_app",
	"uc_browser",
	"uc_browser_hd",
	"uc_browser_mini",
	"ur_browser",
	"vivo_browser",
	"vodafone",
	"wahoo_browser",
	"wechat_app",
	"wetab_browser",
	"webtv_msntv",
	"whatsapp",
	"yahoo_mail_mobile",
	"yahoo_messenger",
	"yahoo_mobile_app",
	"yahoo_slingstone",
	"yahoo!_app",
	"yahoo!_my_browser",
	"yandex_browser",
	"yellowpages_mobile_app",
	"zte",
	"zhihu_app",
	"zimbra_desktop",
}

var Devices = []string{
	"car_entertainment_system",
	"console",
	"desktop",
	"digital_camera",
	"ebook_reader",
	"mobile_device",
	"mobile_phone",
	"tv_device",
	"tablet",
	"unknown",
}

var Platforms = []string{
	"aix",
	"atv_os_x",
	"amiga_os",
	"android",
	"android_for_googletv",
	"asha",
	"bsd",
	"bada",
	"beos",
	"brew",
	"brew_mp",
	"cellos",
	"centos",
	"chromeos",
	"chromecast_os",
	"cygwin",
	"darwin",
	"debian",
	"dragonfly_bsd",
	"fedora",
	"firefoxos",
	"freebsd",
	"hp-ux",
	"haiku",
	"irix64",
	"inferno_os",
	"java",
	"kaios",
	"linux",
	"maui",
	"mac68k",
	"macosx",
	"macppc",
	"maemo",
	"meego",
	"miui_os",
	"mobilinux",
	"netbsd",
	"nintendo_3ds",
	"nintendo_ds",
	"nintendo_dsi",
	"nintendo_switch",
	"nintendo_wii",
	"nintendo_wiiu",
	"os_2",
	"openbsd",
	"openvms",
	"orbisos",
	"palmos",
	"playstation_vita",
	"rim_os",
	"rim_tablet_os",
	"risc_os",
	"red_hat",
	"sailfishos",
	"series30",
	"series40",
	"solaris",
	"sunos",
	"syllable",
	"symbianos",
	"tizen",
	"tru64_unix",
	"ubuntu",
	"ubuntu_touch",
	"unix",
	"win10",
	"win16",
	"win2000",
	"win31",
	"win32",
	"win64",
	"win7",
	"win8",
	"win8.1",
	"win95",
	"win98",
	"win_ce",
	"win_me",
	"winmobile",
	"winnt",
	"winphone",
	"winphone10",
	"winphone6",
	"winphone7",
	"winphone7.10",
	"winphone7.5",
	"winphone7.8",
	"winphone8",
	"winphone8.1",
	"winrt8",
	"winrt8.1",
	"winvista",
	"winxp",
	"wyderos",
	"xbox_360",
	"xbox_360_mobile_view",
	"xbox_os",
	"xbox_os_mobile_view",
	"xbox_os_10",
	"xbox_os_10_mobile_view",
	"xubuntu",
	"ios",
	"ipados",
	"macos",
	"unknown",
	"webos",
}
